#
# copySearchStatsOut.job
#
# This job copies the popularity scores, search count and num listings out of hdfs and puts it
# in the batch pool to be processed by a batch job
#
type=command
#dependencies=allSearchWords,sumSearchView
dependencies=allSearchWords,dedupe
command=${deploydir}/bin/prodCopyAllResults_Alamaula.sh -a 1 -i ${inputdir}/popular_search -k /tmp/keyword_search_sum_alamaula.csv -w /tmp/popularsearchresults_alamaula.csv

