package com.ebay.ecg.bolt.bigdata.pig.udf;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.pig.EvalFunc;
import org.apache.pig.data.Tuple;

public class IsBlacklisted extends EvalFunc<Boolean> {

	private static Map<String,String[]> BLACKLISTMAP = new HashMap<String,String[]>();
	
	private static final String[] IE_BLACKLIST = {
	       "(\\d{3})-(\\d{4})",
	       "(\\d{3})\\W(\\d{4})",
	       "@",
	       "\\.com",
	       "\\@",
	       "\\@hotmail\\.com",
	       "\\@yahoo\\.com",
	       "\\W+(\\d{3})-(\\d{4})\\W+",
	       "\\W+(\\d{3})\\W(\\d{4})\\W+",
	       "\\W+\\.com\\W+",
	       "\\W+\\@hotmail\\.com\\W+",
	       "\\W+\\@yahoo\\.com\\W+",
	       "\\W+[0-9]{3}\\W+[0-9]{3}\\W+",
	       "\\W+2380\\W+lawrence\\W+ave\\W+",
	       "\\W+2nd\\W+chance\\W+automotive\\W+",
	       "\\W+amy\\W+wilkinson\\W+",
	       "\\W+avon\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+in\\W+london\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+of\\W+london\\W+",
	       "\\W+classified\\W+",
	       "\\W+craig\\W+",
	       "\\W+craigslist\\W+",
	       "\\W+default\\W+",
	       "\\W+erotic\\W+",
	       "\\W+escort\\W+",
	       "\\W+escorting\\W+",
	       "\\W+free\\W+",
	       "\\W+google\\W+monito\\W+query\\W+or\\W+googletestad\\W+",
	       "\\W+hotmail\\W+",
	       "\\W+i\\W+am\\W+",
	       "\\W+iupgradecanada\\W+",
	       "\\W+l\\W*e\\W*a\\W*s\\W*e\\W*f\\W*o\\W*l\\W*k\\W*s",
	       "\\W+leasef0lks\\W+",
	       "\\W+leasefolks\\W+",
	       "\\W+massage\\W+",
	       "\\W+sexual massage",
	       "\\W+sensual massage",
	       "\\W+mature massage",
	       "\\W+body to body massage",
	       "\\W+massage parlor",
	       "sexual massage\\W+",
	       "sensual massage\\W+",
	       "mature massage\\W+",
	       "body to body massage\\W+",
	       "massage parlor\\W+",
	       "\\W+sex",
	       "\\W+sex\\W+",
	       "\\W+topless\\W+cleaning\\W+",
	       "\\W+wanted\\W+",
	       "\\W+women\\W+",
	       "\\W+yahoo\\W+",
	       "\\W+year\\W+old\\W+",
	       "\\Wca\\W+",
	       "\\Wcom\\W+",
	       "\\Wnet\\W+",
	       "2\\W*1\\W*4\\W*7\\W*4\\W*8\\W*3\\W*6\\W*4\\W*8",
	       "2\\W*2\\W*6\\W*2\\W*3\\W*4\\W*0\\W*4\\W*1\\W*4",
	       "2\\W*5\\W*0\\W*2\\W*2\\W*5\\W*3\\W*4\\W*6\\W*4",
	       "3\\W*0\\W*6\\W*9\\W*2\\W*2\\W*2\\W*8\\W*0\\W*4",
	       "4\\W*1\\W*6\\W*9\\W*2\\W*2\\W*9\\W*6\\W*3\\W*6",
	       "5\\W*1\\W*4\\W*1\\W*7\\W*8\\W*4\\W*5\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*2\\W*7\\W*2\\W*7\\W*5\\W*7\\W*0",
	       "5\\W*1\\W*4\\W*2\\W*8\\W*1\\W*7\\W*5\\W*5\\W*5",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*1\\W*0\\W*8\\W*7",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*6\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*4\\W*4\\W*4\\W*5\\W*6\\W*7",
	       "5\\W*1\\W*4\\W*4\\W*4\\W*1\\W*2\\W*5\\W*1\\W*8",
	       "5\\W*1\\W*4\\W*5\\W*2\\W*9\\W*9\\W*2\\W*3\\W*4",
	       "5\\W*1\\W*4\\W*5\\W*6\\W*9\\W*0\\W*4\\W*9\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*8",
	       "5\\W*1\\W*4\\W*6\\W*4\\W*1\\W*8\\W*0\\W*3\\W*6",
	       "5\\W*1\\W*9\\W*3\\W*1\\W*9\\W*7\\W*2\\W*0\\W*8",
	       "6\\W*1\\W*3\\W*7\\W*6\\W*4\\W*0\\W*0\\W*5\\W*5",
	       "6\\W*4\\W*7\\W*8\\W*2\\W*7\\W*9\\W*0\\W*8\\W*8",
	       "7\\W*8\\W*0\\W*7\\W*0\\W*8\\W*5\\W*7\\W*1\\W*1",
	       "\\W+adult\\W+",
	       "\\W+allseasonsgiftstore\\W+",
	       "\\W+autoscentral\\.ca\\W+",
	       "\\W+autosontario\\.com\\W+",
	       "\\W+axesmedia\\.com\\W+",
	       "\\W+carloansleamington\\.com\\W+",
	       "\\W+carloanspeterborough\\.com\\W+",
	       "\\W+carloanstimmins\\.com\\W+",
	       "\\W+chris\\W+",
	       "\\W+chris salewski\\W+",
	       "\\W+dating\\W+",
	       "\\W+discountsweet\\.com\\W+",
	       "\\W+escort\\W+",
	       "\\W+escorte\\W+",
	       "\\W+femme\\W+",
	       "\\W+free\\W+",
	       "\\W+gmail\\W+",
	       "\\W+googletestad\\W+",
	       "\\W+hotmail\\W+",
	       "\\W+javascript\\W+",
	       "\\W+m4m\\W+",
	       "\\W+m4w\\W+",
	       "\\W+newweightlosstrials\\.com\\W+",
	       "\\W+nude\\W+",
	       "\\W+porn\\W+",
	       "\\W+usedcarsbarrie\\.ca\\W+",
	       "\\W+usedcarshamilton\\.com\\W+",
	       "\\W+usedcarssaintcatherines\\.ca\\W+",
	       "\\W+usedcarswoodstock\\.ca\\W+",
	       "\\W+w4m\\W+",
	       "\\W+w4w\\W+",
	       "\\W+wegetyoudriving\\.com\\W+",
	       "\\W+www\\W+",
	       "\\W+www.revenusemail\\.com\\W+",
	       "\\W+yahoo\\W+",
	       "adult",
	       "allseasonsgiftstore",
	       "autoscentral\\.ca",
	       "autosontario\\.com",
	       "axesmedia\\.com",
	       "carloansleamington\\.com",
	       "carloanspeterborough\\.com",
	       "carloanstimmins\\.com",
	       "chris",
	       "chris salewski",
	       "dating",
	       "discountsweet\\.com",
	       "escort",
	       "escorte",
	       "femme",
	       "free",
	       "gmail",
	       "googletestad",
	       "hotmail",
	       "javascript",
	       "m4m",
	       "m4w",
	       "massage",
	       "newweightlosstrials\\.com",
	       "nude",
	       "porn",
	       "usedcarsbarrie\\.ca",
	       "usedcarshamilton\\.com",
	       "usedcarssaintcatherines\\.ca",
	       "usedcarswoodstock\\.ca",
	       "w4m",
	       "w4w",
	       "wegetyoudriving\\.com",
	       "www",
	       "www.revenusemail\\.com",
	       "yahoo",
	       "^((\\d+)*\\s*)*$"
	};

	private static final String[] ZA_BLACKLIST = {
	       "(\\d{3})-(\\d{4})",
	       "(\\d{3})\\W(\\d{4})",
	       "@",
	       "\\.com",
	       "\\@",
	       "\\@hotmail\\.com",
	       "\\@yahoo\\.com",
	       "\\W+(\\d{3})-(\\d{4})\\W+",
	       "\\W+(\\d{3})\\W(\\d{4})\\W+",
	       "\\W+\\.com\\W+",
	       "\\W+\\@hotmail\\.com\\W+",
	       "\\W+\\@yahoo\\.com\\W+",
	       "\\W+[0-9]{3}\\W+[0-9]{3}\\W+",
	       "\\W+2380\\W+lawrence\\W+ave\\W+",
	       "\\W+2nd\\W+chance\\W+automotive\\W+",
	       "\\W+amy\\W+wilkinson\\W+",
	       "\\W+avon\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+in\\W+london\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+of\\W+london\\W+",
	       "\\W+classified\\W+",
	       "\\W+craig\\W+",
	       "\\W+craigslist\\W+",
	       "\\W+default\\W+",
	       "\\W+erotic\\W+",
	       "\\W+escort\\W+",
	       "\\W+escorting\\W+",
	       "\\W+free\\W+",
	       "\\W+google\\W+monito\\W+query\\W+or\\W+googletestad\\W+",
	       "\\W+hotmail\\W+",
	       "\\W+i\\W+am\\W+",
	       "\\W+iupgradecanada\\W+",
	       "\\W+l\\W*e\\W*a\\W*s\\W*e\\W*f\\W*o\\W*l\\W*k\\W*s",
	       "\\W+leasef0lks\\W+",
	       "\\W+leasefolks\\W+",
	       "\\W+massage\\W+",
	       "\\W+sexual massage",
	       "\\W+sensual massage",
	       "\\W+mature massage",
	       "\\W+body to body massage",
	       "\\W+massage parlor",
	       "sexual massage\\W+",
	       "sensual massage\\W+",
	       "mature massage\\W+",
	       "body to body massage\\W+",
	       "massage parlor\\W+",
	       "\\W+sex",
	       "\\W+sex\\W+",
	       "\\W+topless\\W+cleaning\\W+",
	       "\\W+wanted\\W+",
	       "\\W+women\\W+",
	       "\\W+yahoo\\W+",
	       "\\W+year\\W+old\\W+",
	       "\\Wca\\W+",
	       "\\Wcom\\W+",
	       "\\Wnet\\W+",
	       "2\\W*1\\W*4\\W*7\\W*4\\W*8\\W*3\\W*6\\W*4\\W*8",
	       "2\\W*2\\W*6\\W*2\\W*3\\W*4\\W*0\\W*4\\W*1\\W*4",
	       "2\\W*5\\W*0\\W*2\\W*2\\W*5\\W*3\\W*4\\W*6\\W*4",
	       "3\\W*0\\W*6\\W*9\\W*2\\W*2\\W*2\\W*8\\W*0\\W*4",
	       "4\\W*1\\W*6\\W*9\\W*2\\W*2\\W*9\\W*6\\W*3\\W*6",
	       "5\\W*1\\W*4\\W*1\\W*7\\W*8\\W*4\\W*5\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*2\\W*7\\W*2\\W*7\\W*5\\W*7\\W*0",
	       "5\\W*1\\W*4\\W*2\\W*8\\W*1\\W*7\\W*5\\W*5\\W*5",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*1\\W*0\\W*8\\W*7",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*6\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*4\\W*4\\W*4\\W*5\\W*6\\W*7",
	       "5\\W*1\\W*4\\W*4\\W*4\\W*1\\W*2\\W*5\\W*1\\W*8",
	       "5\\W*1\\W*4\\W*5\\W*2\\W*9\\W*9\\W*2\\W*3\\W*4",
	       "5\\W*1\\W*4\\W*5\\W*6\\W*9\\W*0\\W*4\\W*9\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*8",
	       "5\\W*1\\W*4\\W*6\\W*4\\W*1\\W*8\\W*0\\W*3\\W*6",
	       "5\\W*1\\W*9\\W*3\\W*1\\W*9\\W*7\\W*2\\W*0\\W*8",
	       "6\\W*1\\W*3\\W*7\\W*6\\W*4\\W*0\\W*0\\W*5\\W*5",
	       "6\\W*4\\W*7\\W*8\\W*2\\W*7\\W*9\\W*0\\W*8\\W*8",
	       "7\\W*8\\W*0\\W*7\\W*0\\W*8\\W*5\\W*7\\W*1\\W*1",
	       "\\W+adult\\W+",
	       "\\W+allseasonsgiftstore\\W+",
	       "\\W+autoscentral\\.ca\\W+",
	       "\\W+autosontario\\.com\\W+",
	       "\\W+axesmedia\\.com\\W+",
	       "\\W+carloansleamington\\.com\\W+",
	       "\\W+carloanspeterborough\\.com\\W+",
	       "\\W+carloanstimmins\\.com\\W+",
	       "\\W+chris\\W+",
	       "\\W+chris salewski\\W+",
	       "\\W+dating\\W+",
	       "\\W+discountsweet\\.com\\W+",
	       "\\W+escort\\W+",
	       "\\W+escorte\\W+",
	       "\\W+femme\\W+",
	       "\\W+free\\W+",
	       "\\W+gmail\\W+",
	       "\\W+googletestad\\W+",
	       "\\W+hotmail\\W+",
	       "\\W+javascript\\W+",
	       "\\W+m4m\\W+",
	       "\\W+m4w\\W+",
	       "\\W+massage\\W+",
	       "\\W+newweightlosstrials\\.com\\W+",
	       "\\W+nude\\W+",
	       "\\W+porn\\W+",
	       "\\W+usedcarsbarrie\\.ca\\W+",
	       "\\W+usedcarshamilton\\.com\\W+",
	       "\\W+usedcarssaintcatherines\\.ca\\W+",
	       "\\W+usedcarswoodstock\\.ca\\W+",
	       "\\W+w4m\\W+",
	       "\\W+w4w\\W+",
	       "\\W+wegetyoudriving\\.com\\W+",
	       "\\W+www\\W+",
	       "\\W+www.revenusemail\\.com\\W+",
	       "\\W+yahoo\\W+",
	       "adult",
	       "allseasonsgiftstore",
	       "autoscentral\\.ca",
	       "autosontario\\.com",
	       "axesmedia\\.com",
	       "carloansleamington\\.com",
	       "carloanspeterborough\\.com",
	       "carloanstimmins\\.com",
	       "chris",
	       "chris salewski",
	       "dating",
	       "discountsweet\\.com",
	       "escort",
	       "escorte",
	       "femme",
	       "free",
	       "gmail",
	       "googletestad",
	       "hotmail",
	       "javascript",
	       "m4m",
	       "m4w",
	       "massage",
	       "newweightlosstrials\\.com",
	       "nude",
	       "porn",
	       "usedcarsbarrie\\.ca",
	       "usedcarshamilton\\.com",
	       "usedcarssaintcatherines\\.ca",
	       "usedcarswoodstock\\.ca",
	       "w4m",
	       "w4w",
	       "wegetyoudriving\\.com",
	       "www",
	       "www.revenusemail\\.com",
	       "yahoo",
	       "^((\\d+)*\\s*)*$"
	};
	
	private static final String[] MX_BLACKLIST = {
	       "\\W+.com\\W+",
	       "\\W+adolecentes\\W+",
	       "\\W+ala maula\\W+",
	       "\\W+alamaula\\W+",
	       "\\W+amante\\W+",
	       "\\W+amateur\\W+",
	       "\\W+anal\\W+",
	       "\\W+atrevida\\W+",
	       "\\W+aviso\\W+",
	       "\\W+bajinal\\W+",
	       "\\W+ba�andose\\W+",
	       "\\W+besandose\\W+",
	       "\\W+beso\\W+",
	       "\\W+bribrador\\W+",
	       "\\W+cachonda\\W+",
	       "\\W+chippendale\\W+",
	       "\\W+clubtj69\\W+",
	       "\\W+cocaina\\W+",
	       "\\W+cogida\\W+",
	       "\\W+colegialas\\W+",
	       "\\W+concha\\W+",
	       "\\W+consolador\\W+",
	       "\\W+culo\\W+",
	       "\\W+depilaci\\W+",
	       "\\W+desnud\\W+",
	       "\\W+despedida\\W+",
	       "\\W+digitalmobilestores\\W+",
	       "\\W+droga\\W+",
	       "\\W+ebay\\W+",
	       "\\W+embrel\\W+",
	       "\\W+en pelota\\W+",
	       "\\W+enbrel\\W+",
	       "\\W+erotic\\W+",
	       "\\W+escort\\W+",
	       "\\W+estafa\\W+",
	       "\\W+estibas\\W+",
	       "\\W+estrip\\W+",
	       "\\W+etanercept\\W+",
	       "\\W+fake\\W+",
	       "\\W+folla\\W+",
	       "\\W+fraude\\W+",
	       "\\W+gmail\\W+",
	       "\\W+google\\W+",
	       "\\W+gozar\\W+",
	       "\\W+haceb\\W+",
	       "\\W+hotm\\W+",
	       "\\W+huagpas\\W+",
	       "\\W+imagen\\W+",
	       "\\W+jovensitas\\W+",
	       "\\W+lesbi\\W+",
	       "\\W+lolita\\W+",
	       "\\W+maduras\\W+",
	       "\\W+mamada\\W+",
	       "\\W+marihuana\\W+",
	       "\\W+market_arena\\W+",
	       "\\W+masaje\\W+",
	       "\\W+menor\\W+",
	       "\\W+minivestidos\\W+",
	       "\\W+morbosa\\W+",
	       "\\W+mujeres adultas\\W+",
	       "\\W+nenas\\W+",
	       "\\W+olx\\W+",
	       "\\W+orgasmo\\W+",
	       "\\W+oxaprost\\W+",
	       "\\W+pene\\W+",
	       "\\W+petarda\\W+",
	       "\\W+pito\\W+",
	       "\\W+pono\\W+",
	       "\\W+porn\\W+",
	       "\\W+porno\\W+",
	       "\\W+porografico\\W+",
	       "\\W+poto\\W+",
	       "\\W+prestamo\\W+",
	       "\\W+prohibida\\W+",
	       "\\W+prostatico\\W+",
	       "\\W+puta\\W+",
	       "\\W+putas\\W+",
	       "\\W+puto\\W+",
	       "\\W+sa de cv\\W+",
	       "\\W+se�oras\\W+",
	       "\\W+sex\\W+",
	       "\\W+sexso\\W+",
	       "\\W+sin ropa\\W+",
	       "\\W+solo para mujeres\\W+",
	       "\\W+streep\\W+",
	       "\\W+strep\\W+",
	       "\\W+strip\\W+",
	       "\\W+sumisa\\W+",
	       "\\W+swinger\\W+",
	       "\\W+teta\\W+",
	       "\\W+vagina\\W+",
	       "\\W+vajinal\\W+",
	       "\\W+verga\\W+",
	       "\\W+viagra\\W+",
	       "\\W+vibrador\\W+",
	       "\\W+warranty\\W+",
	       "\\W+webcam\\W+",
	       "\\W+www\\W+",
	       "\\W+xxx\\W+",
	       "\\W+yahoo\\W+",
	       "\\W+zoofi\\W+",
	       ".com",
	       "adolecentes",
	       "ala maula",
	       "alamaula",
	       "amante",
	       "amateur",
	       "anal",
	       "atrevida",
	       "aviso",
	       "bajinal",
	       "ba�andose",
	       "besandose",
	       "beso",
	       "bribrador",
	       "cachonda",
	       "chippendale",
	       "clubtj69",
	       "cocaina",
	       "cogida",
	       "colegialas",
	       "concha",
	       "consolador",
	       "culo",
	       "depilaci",
	       "desnud",
	       "despedida",
	       "digitalmobilestores",
	       "droga",
	       "ebay",
	       "embrel",
	       "en pelota",
	       "enbrel",
	       "erotic",
	       "escort",
	       "estafa",
	       "estibas",
	       "estrip",
	       "etanercept",
	       "fake",
	       "folla",
	       "fraude",
	       "gmail",
	       "google",
	       "gozar",
	       "haceb",
	       "hotm",
	       "huagpas",
	       "imagen",
	       "jovensitas",
	       "lesbi",
	       "lolita",
	       "maduras",
	       "mamada",
	       "marihuana",
	       "market_arena",
	       "masaje",
	       "menor",
	       "minivestidos",
	       "morbosa",
	       "mujeres adultas",
	       "nenas",
	       "olx",
	       "orgasmo",
	       "oxaprost",
	       "pene",
	       "petarda",
	       "pito",
	       "pono",
	       "porn",
	       "porno",
	       "porografico",
	       "poto",
	       "prestamo",
	       "prohibida",
	       "prostatico",
	       "puta",
	       "putas",
	       "puto",
	       "sa de cv",
	       "se�oras",
	       "sex",
	       "sexso",
	       "sin ropa",
	       "solo para mujeres",
	       "streep",
	       "strep",
	       "strip",
	       "sumisa",
	       "swinger",
	       "teta",
	       "vagina",
	       "vajinal",
	       "verga",
	       "viagra",
	       "vibrador",
	       "warranty",
	       "webcam",
	       "www",
	       "xxx",
	       "yahoo",
	       "zoofi",
	       "^((\\d+)*\\s*)*$"
	};
	
	private static final String[] US_BLACKLIST = {
	       "(\\d{3})-(\\d{4})",
	       "(\\d{3})\\W(\\d{4})",
	       "\\W+.com \\W+",
	       "@",
	       "\\W+\\.com\\W+",
	       "\\W+\\@\\W+",
	       "\\W+\\@hotmail\\.com\\W+",
	       "\\@yahoo\\.com",
	       "\\W+[0-9]{3}\\W+[0-9]{3}\\W+",
	       "\\W+2380\\W+lawrence\\W+ave\\W+",
	       "\\W+2nd\\W+chance\\W+automotive\\W+",
	       "\\W+amy\\W+wilkinson\\W+",
	       "\\W+avon\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+in\\W+london\\W+",
	       "\\W+canadian\\W+auto\\W+group\\W+of\\W+london\\W+",
	       "\\W+classified\\W+",
	       "\\W+craig\\W+",
	       "\\W+craigslist\\W+",
	       "\\W+default\\W+",
	       "\\W+erotic\\W+",
	       "\\W+escort\\W+",
	       "\\W+escorting\\W+",
	       "\\W+free\\W+",
	       "\\W+google\\W+monito\\W+query\\W+or\\W+googletestad\\W+",
	       "\\W+hotmail\\W+",
	       "\\W+i\\W+am\\W+",
	       "\\W+iupgradecanada\\W+",
	       "\\W+l\\W*e\\W*a\\W*s\\W*e\\W*f\\W*o\\W*l\\W*k\\W*s",
	       "\\W+leasef0lks\\W+",
	       "\\W+leasefolks\\W+",
	       "\\W+massage\\W+",
	       "\\W+sex",
	       "\\W+sex\\W+",
	       "\\W+topless\\W+cleaning\\W+",
	       "\\W+wanted\\W+",
	       "\\W+women\\W+",
	       "\\W+yahoo\\W+",
	       "\\W+year\\W+old\\W+",
	       "\\Wca\\W+",
	       "\\Wcom\\W+",
	       "\\Wnet\\W+",
	       "2\\W*1\\W*4\\W*7\\W*4\\W*8\\W*3\\W*6\\W*4\\W*8",
	       "2\\W*2\\W*6\\W*2\\W*3\\W*4\\W*0\\W*4\\W*1\\W*4",
	       "2\\W*5\\W*0\\W*2\\W*2\\W*5\\W*3\\W*4\\W*6\\W*4",
	       "3\\W*0\\W*6\\W*9\\W*2\\W*2\\W*2\\W*8\\W*0\\W*4",
	       "4\\W*1\\W*6\\W*9\\W*2\\W*2\\W*9\\W*6\\W*3\\W*6",
	       "5\\W*1\\W*4\\W*1\\W*7\\W*8\\W*4\\W*5\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*2\\W*7\\W*2\\W*7\\W*5\\W*7\\W*0",
	       "5\\W*1\\W*4\\W*2\\W*8\\W*1\\W*7\\W*5\\W*5\\W*5",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*1\\W*0\\W*8\\W*7",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*4\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*3\\W*6\\W*9\\W*3\\W*2\\W*6",
	       "5\\W*1\\W*4\\W*3\\W*4\\W*4\\W*4\\W*5\\W*6\\W*7",
	       "5\\W*1\\W*4\\W*4\\W*4\\W*1\\W*2\\W*5\\W*1\\W*8",
	       "5\\W*1\\W*4\\W*5\\W*2\\W*9\\W*9\\W*2\\W*3\\W*4",
	       "5\\W*1\\W*4\\W*5\\W*6\\W*9\\W*0\\W*4\\W*9\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*5",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*6",
	       "5\\W*1\\W*4\\W*5\\W*7\\W*8\\W*1\\W*7\\W*8\\W*8",
	       "5\\W*1\\W*4\\W*6\\W*4\\W*1\\W*8\\W*0\\W*3\\W*6",
	       "5\\W*1\\W*9\\W*3\\W*1\\W*9\\W*7\\W*2\\W*0\\W*8",
	       "6\\W*1\\W*3\\W*7\\W*6\\W*4\\W*0\\W*0\\W*5\\W*5",
	       "6\\W*4\\W*7\\W*8\\W*2\\W*7\\W*9\\W*0\\W*8\\W*8",
	       "7\\W*8\\W*0\\W*7\\W*0\\W*8\\W*5\\W*7\\W*1\\W*1",
	       "\\W+adolecentes\\W+",
	       "\\W+adult\\W+",
	       "\\W+ala maula\\W+",
	       "\\W+alamaula \\W+",
	       "\\W+allseasonsgiftstore\\W+",
	       "\\W+amante \\W+",
	       "\\W+amateur \\W+",
	       "\\W+anal \\W+",
	       "\\W+atrevida \\W+",
	       "\\W+autoscentral\\.ca\\W+",
	       "\\W+autosontario\\.com\\W+",
	       "\\W+aviso \\W+",
	       "\\W+axesmedia\\.com\\W+",
	       "\\W+bajinal \\W+",
	       "\\W+ba�andose \\W+",
	       "\\W+besandose \\W+",
	       "\\W+beso \\W+",
	       "\\W+bribrador \\W+",
	       "\\W+cachonda \\W+",
	       "\\W+carloansleamington\\.com\\W+",
	       "\\W+carloanspeterborough\\.com\\W+",
	       "\\W+carloanstimmins\\.com\\W+",
	       "\\W+chippendale \\W+",
	       "\\W+chris\\W+",
	       "\\W+chris salewski\\W+",
	       "\\W+clubtj69 \\W+",
	       "\\W+cocaina \\W+",
	       "\\W+cogida \\W+",
	       "\\W+colegialas \\W+",
	       "\\W+concha \\W+",
	       "\\W+consolador \\W+",
	       "\\W+culo \\W+",
	       "\\W+dating\\W+",
	       "\\W+depilaci \\W+",
	       "\\W+desnud \\W+",
	       "\\W+despedida \\W+",
	       "\\W+digitalmobilestores \\W+",
	       "\\W+discountsweet\\.com\\W+",
	       "\\W+droga \\W+",
	       "\\W+ebay \\W+",
	       "\\W+embrel \\W+",
	       "\\W+en pelota\\W+",
	       "\\W+enbrel \\W+",
	       "\\W+erotic \\W+",
	       "\\W+escort\\W+",
	       "\\W+escort \\W+",
	       "\\W+escorte\\W+",
	       "\\W+estafa \\W+",
	       "\\W+estibas \\W+",
	       "\\W+estrip \\W+",
	       "\\W+etanercept \\W+",
	       "\\W+fake \\W+",
	       "\\W+femme\\W+",
	       "\\W+folla \\W+",
	       "\\W+fraude \\W+",
	       "\\W+free\\W+",
	       "\\W+gmail\\W+",
	       "\\W+gmail \\W+",
	       "\\W+google \\W+",
	       "\\W+googletestad\\W+",
	       "\\W+gozar \\W+",
	       "\\W+haceb \\W+",
	       "\\W+hotm \\W+",
	       "\\W+hotmail\\W+",
	       "\\W+huagpas \\W+",
	       "\\W+imagen \\W+",
	       "\\W+javascript\\W+",
	       "\\W+jovensitas \\W+",
	       "\\W+lesbi \\W+",
	       "\\W+lolita \\W+",
	       "\\W+m4m\\W+",
	       "\\W+m4w\\W+",
	       "\\W+maduras \\W+",
	       "\\W+mamada \\W+",
	       "\\W+marihuana \\W+",
	       "\\W+market_arena \\W+",
	       "\\W+masaje \\W+",
	       "\\W+massage\\W+",
	       "\\W+menor \\W+",
	       "\\W+minivestidos \\W+",
	       "\\W+morbosa \\W+",
	       "\\W+mujeres adultas\\W+",
	       "\\W+nenas \\W+",
	       "\\W+newweightlosstrials\\.com\\W+",
	       "\\W+nude\\W+",
	       "\\W+olx \\W+",
	       "\\W+orgasmo \\W+",
	       "\\W+oxaprost \\W+",
	       "\\W+pene \\W+",
	       "\\W+petarda \\W+",
	       "\\W+pito \\W+",
	       "\\W+pono \\W+",
	       "\\W+porn\\W+",
	       "\\W+porn \\W+",
	       "\\W+porno \\W+",
	       "\\W+porografico \\W+",
	       "\\W+poto \\W+",
	       "\\W+prestamo \\W+",
	       "\\W+prohibida \\W+",
	       "\\W+prostatico \\W+",
	       "\\W+puta \\W+",
	       "\\W+putas \\W+",
	       "\\W+puto \\W+",
	       "\\W+sa de cv\\W+",
	       "\\W+se�oras \\W+",
	       "\\W+sex \\W+",
	       "\\W+sexso \\W+",
	       "\\W+sin ropa\\W+",
	       "\\W+solo para mujeres\\W+",
	       "\\W+streep \\W+",
	       "\\W+strep \\W+",
	       "\\W+strip \\W+",
	       "\\W+sumisa \\W+",
	       "\\W+swinger \\W+",
	       "\\W+teta \\W+",
	       "\\W+usedcarsbarrie\\.ca\\W+",
	       "\\W+usedcarshamilton\\.com\\W+",
	       "\\W+usedcarssaintcatherines\\.ca\\W+",
	       "\\W+usedcarswoodstock\\.ca\\W+",
	       "\\W+vagina \\W+",
	       "\\W+vajinal \\W+",
	       "\\W+verga \\W+",
	       "\\W+viagra \\W+",
	       "\\W+vibrador \\W+",
	       "\\W+w4m\\W+",
	       "\\W+w4w\\W+",
	       "\\W+warranty \\W+",
	       "\\W+webcam \\W+",
	       "\\W+wegetyoudriving\\.com\\W+",
	       "\\W+www\\W+",
	       "\\W+www \\W+",
	       "\\W+www.revenusemail\\.com\\W+",
	       "\\W+xxx \\W+",
	       "\\W+yahoo\\W+",
	       "\\W+yahoo \\W+",
	       "\\W+zoofi\\W+ ",
		   "adolecentes",
	       "ala maula",
	       "alamaula",
	       "amante",
	       "amateur",
	       "anal",
	       "atrevida",
	       "aviso",
	       "bajinal",
	       "ba�andose",
	       "besandose",
	       "beso",
	       "bribrador",
	       "cachonda",
	       "chippendale",
	       "clubtj69",
	       "cocaina",
	       "cogida",
	       "colegialas",
	       "concha",
	       "consolador",
	       "culo",
	       "depilaci",
	       "desnud",
	       "despedida",
	       "digitalmobilestores",
	       "droga",
	       "ebay",
	       "embrel",
	       "en pelota",
	       "enbrel",
	       "erotic",
	       "escort",
	       "estafa",
	       "estibas",
	       "estrip",
	       "etanercept",
	       "fake",
	       "folla",
	       "fraude",
	       "gmail",
	       "google",
	       "gozar",
	       "haceb",
	       "hotm",
	       "huagpas",
	       "imagen",
	       "jovensitas",
	       "lesbi",
	       "lolita",
	       "maduras",
	       "mamada",
	       "marihuana",
	       "market_arena",
	       "masaje",
	       "menor",
	       "minivestidos",
	       "morbosa",
	       "mujeres adultas",
	       "nenas",
	       "olx",
	       "orgasmo",
	       "oxaprost",
	       "pene",
	       "petarda",
	       "pito",
	       "pono",
	       "porn",
	       "porno",
	       "porografico",
	       "poto",
	       "prestamo",
	       "prohibida",
	       "prostatico",
	       "puta",
	       "putas",
	       "puto",
	       "sa de cv",
	       "se�oras",
	       "sex",
	       "sexso",
	       "sin ropa",
	       "solo para mujeres",
	       "streep",
	       "strep",
	       "strip",
	       "sumisa",
	       "swinger",
	       "teta",
	       "vagina",
	       "vajinal",
	       "verga",
	       "viagra",
	       "vibrador",
	       "warranty",
	       "webcam",
	       "www",
	       "xxx",
	       "yahoo",
	       "zoofi",
	       "^((\\d+)*\\s*)*$"
	};
	
	static {
		BLACKLISTMAP.put("ZA", ZA_BLACKLIST);
		BLACKLISTMAP.put("IE", IE_BLACKLIST);
		BLACKLISTMAP.put("MX", MX_BLACKLIST); // Assumes iBazar and VNS have the same blacklist
		BLACKLISTMAP.put("US", US_BLACKLIST);
	}

	public Boolean exec(Tuple input) throws IOException {
		
		Boolean returnval = false;
		
		if (input == null || input.size() == 0)
			return null;

		String country = (String) input.get(0);  // this is the country
		
		if (country == null || country.length() == 0) return false;
		
		String[] countryBlacklist = BLACKLISTMAP.get(country);
		// TODO look for the blacklist related to the country
		String word = (String) input.get(1); 	// this is the word to check
		
		
		returnval = hasBlacklistedKeyword(word, countryBlacklist);
		return returnval;
	}

	/**
	 * Check if the keyword phrase has blacklisted words enumerated in the String[] array
	 * 
	 * @param keyword					Phrase to check
	 * @param blacklistedKeywords		List of blacklisted keywords
	 * @return
	 */
	public static Boolean hasBlacklistedKeyword(String keyword, String[] blacklistedKeywords) {
		if (keyword == null || keyword.length() == 0 || blacklistedKeywords == null || blacklistedKeywords.length == 0) return false;
		for (String expression : blacklistedKeywords) {
			Pattern testPattern = Pattern.compile(expression);
			Matcher testMatcher = testPattern.matcher(keyword);
			if (testMatcher.find()) return true;
		}
		return false;
	}

	
	public static void main(String[] args) {
		IsBlacklisted ier = new IsBlacklisted();
		String country = "IE";
		String keyword = "sex";
		String testVal = "any " + keyword + " word";
		String[] blacklist = BLACKLISTMAP.get(country);
		Boolean domainStr = ier.hasBlacklistedKeyword(testVal, blacklist);
		System.out.println("Value: "+testVal+" is blacklisted?"+domainStr);

		 testVal = "simple "+ keyword;
		 domainStr = ier.hasBlacklistedKeyword(testVal, blacklist);
		System.out.println("Value: "+testVal+" is blacklisted?"+domainStr);

		 testVal = keyword + " items";
		 domainStr = ier.hasBlacklistedKeyword(testVal, blacklist);
		System.out.println("Value: "+testVal+" is blacklisted?"+domainStr);

		 testVal = "simple "+ keyword + " items";
		 domainStr = ier.hasBlacklistedKeyword(testVal, blacklist);
		System.out.println("Value: "+testVal+" is blacklisted?"+domainStr);

		 testVal = "simple  items";
		 domainStr = ier.hasBlacklistedKeyword(testVal, blacklist);
		System.out.println("Value: "+testVal+" is blacklisted?"+domainStr);

	}
}
